[project]
name = "audiocompression"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = [
    "librosa>=0.11.0",
    "numpy>=2.2.4",
]
