[project]
name = "audiocompression"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = [
    "librosa>=0.11.0",
    "tensorflow>=2.19.0",
]
